export const TICKER_LIST = [
  { value: "005930", name: "삼성전자 🇰🇷" },
  { value: "000660", name: "SK하이닉스 🇰🇷" },
  { value: "035420", name: "NAVER 🇰🇷" },
  { value: "005380", name: "현대차 🇰🇷" },
  { value: "051910", name: "LG화학 🇰🇷" },
  { value: "006400", name: "삼성SDI 🇰🇷" },
  { value: "035720", name: "카카오 🇰🇷" },
  { value: "207940", name: "삼성바이오로직스 🇰🇷" },
  { value: "028260", name: "삼성물산 🇰🇷" },
  { value: "000270", name: "기아 🇰🇷" },
  { value: "068270", name: "셀트리온 🇰🇷" },
  { value: "105560", name: "KB금융 🇰🇷" },
  { value: "055550", name: "신한지주 🇰🇷" },
  { value: "032830", name: "삼성생명 🇰🇷" },
  { value: "086790", name: "하나금융지주 🇰🇷" },
  { value: "017670", name: "SK텔레콤 🇰🇷" },
  { value: "030200", name: "KT 🇰🇷" },
  { value: "003550", name: "LG 🇰🇷" },
  { value: "066570", name: "LG전자 🇰🇷" },
  { value: "SPY",   name: "S&P500 ETF 🇺🇸" },
  { value: "QQQ",   name: "나스닥100 ETF 🇺🇸" },
  { value: "AAPL",  name: "애플 🇺🇸" },
  { value: "TSLA",  name: "테슬라 🇺🇸" },
  { value: "NVDA",  name: "엔비디아 🇺🇸" },
  { value: "MSFT",  name: "마이크로소프트 🇺🇸" },
  { value: "AMZN",  name: "아마존 🇺🇸" },
  { value: "META",  name: "메타 🇺🇸" },
  { value: "GOOGL", name: "구글 🇺🇸" },
  { value: "NFLX",  name: "넷플릭스 🇺🇸" },
  { value: "AMD",   name: "AMD 🇺🇸" },
  { value: "INTC",  name: "인텔 🇺🇸" },
  { value: "TSM",   name: "TSMC 🇺🇸" },
  { value: "V",     name: "비자 🇺🇸" },
  { value: "MA",    name: "마스터카드 🇺🇸" },
  { value: "JPM",   name: "JP모건 🇺🇸" },
  { value: "DIS",   name: "디즈니 🇺🇸" },
  { value: "WMT",   name: "월마트 🇺🇸" },
  { value: "COIN",  name: "코인베이스 🇺🇸" },
  { value: "PLTR",  name: "팔란티어 🇺🇸" },
];

export const CRYPTO_LIST = [
  { value: "BTCUSDT",  name: "비트코인" },
  { value: "ETHUSDT",  name: "이더리움" },
  { value: "SOLUSDT",  name: "솔라나" },
  { value: "XRPUSDT",  name: "리플" },
  { value: "BNBUSDT",  name: "BNB" },
  { value: "DOGEUSDT", name: "도지코인" },
  { value: "ADAUSDT",  name: "에이다" },
];

export const ORDER_TYPES = [
  { value: "LIMIT",  label: "보통(지정가)" },
  { value: "MARKET", label: "시장가" },
  { value: "LOC",    label: "LOC(장마감)" },
];

export const LIMIT_SUB_TYPES = ["정규장", "장전시간외", "장후시간외", "조건부지정가", "최유리지정가", "최우선지정가"];
