"""
포지션 스케일링 전략(IB/VR) → 독립 실행 가능한 파이썬 코드 생성.

generate_portfolio_strategy(strategy, config) → str(.py 소스).
생성된 코드의 run(closes, highs=None) 는 라이브 엔진과 **동일 알고리즘**을 인라인하므로
결과가 1:1 일치한다(tests/test_codegen_engine_parity.py 가 강제).

config 키는 엔진 파라미터(InfiniteBuyingParams / ValueRebalancingParams)와 동일하게 맞춰
'워크스페이스 config == codegen 입력 == 엔진 입력' 3자 일치를 구조적으로 보장한다.
"""
from __future__ import annotations
from typing import Dict, Any

PORTFOLIO_STRATEGIES = ("infinite_buying", "value_rebalancing")

_HEADER = '''# ─────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED by Alpha-Helix codegen — {title}
# 이 코드는 워크스페이스 설정(config)을 그대로 박아 만든 **독립 실행 전략**입니다.
# run(closes, highs) 결과 == Alpha-Helix analytics 엔진({engine_fn}) 결과 (parity 테스트로 보장).
# 의존성: numpy, pandas 만. (시세는 사용자가 closes 로 주입)
# ─────────────────────────────────────────────────────────────────────────────
from __future__ import annotations
import numpy as np
import pandas as pd


def _round(x, n=4):
    try:
        v = float(x)
        return None if (np.isnan(v) or np.isinf(v)) else round(v, n)
    except Exception:
        return None
'''

# ── 무한매수법(IB) — run_infinite_buying 의 매매루프를 1:1 미러링한 고정 본문 ──
_IB_BODY = '''

def run(closes, highs=None):
    """closes={ticker: pd.Series(close)}; highs(선택)={ticker: pd.Series(high)} 주면 익절 지정가 체결."""
    tickers = list(closes.keys())
    if not tickers:
        raise ValueError("at least one ticker required")
    df = pd.concat({t: closes[t] for t in tickers}, axis=1).sort_index().ffill().dropna(how="all")
    high_df = None
    if highs:
        cols = {t: highs.get(t) for t in tickers if highs.get(t) is not None}
        if cols:
            high_df = pd.concat(cols, axis=1).reindex(df.index).ffill()

    per_asset_capital = INITIAL_CAPITAL / len(tickers)
    states = {t: {"cash": per_asset_capital, "qty": 0.0, "cost_basis": 0.0, "avg_price": 0.0,
                  "cycle_idx": 0.0, "cycle_budget": per_asset_capital / SPLIT,
                  "realized_pnl": 0.0, "trades": 0, "cycles_completed": 0} for t in tickers}
    equity_history = []

    for ts, row in df.iterrows():
        for t in tickers:
            price = row.get(t)
            if price is None or pd.isna(price) or price <= 0:
                continue
            s = states[t]
            budget = s["cycle_budget"]

            # 1) 익절 — 평단×(1+tp) 지정가. 장중 고가가 닿으면 그 가로 전량 체결(High 없으면 종가).
            if s["qty"] > 0 and s["avg_price"] > 0:
                trigger = s["avg_price"] * (1.0 + TAKE_PROFIT_PCT / 100.0)
                day_high = None
                if high_df is not None and t in high_df.columns:
                    try:
                        hv = high_df.at[ts, t]
                        day_high = float(hv) if hv is not None and not pd.isna(hv) else None
                    except Exception:
                        day_high = None
                hit = (day_high >= trigger) if day_high is not None else (price >= trigger)
                if hit:
                    sell_price = trigger
                    proceeds = s["qty"] * sell_price
                    fee = proceeds * FEES
                    net = proceeds - fee
                    s["realized_pnl"] += net - s["cost_basis"]
                    s["cash"] += net
                    s["trades"] += 1
                    s["qty"] = 0.0
                    s["cost_basis"] = 0.0
                    s["avg_price"] = 0.0
                    s["cycle_idx"] = 0
                    s["cycles_completed"] += 1
                    s["cycle_budget"] = s["cash"] / SPLIT if s["cash"] > 0 else s["cycle_budget"]
                    continue

            # 2) 매수
            if s["cycle_idx"] >= SPLIT:
                continue
            if s["avg_price"] <= 0 or price <= s["avg_price"]:
                buy_fraction = 1.0
            elif price <= s["avg_price"] * (1.0 + LOC_OFFSET_PCT / 100.0):
                buy_fraction = 0.5
            else:
                continue

            amount = budget * buy_fraction
            if amount > s["cash"]:
                amount = s["cash"]
            if amount <= 0:
                continue
            buy_price = price * (1.0 + SLIPPAGE)
            qty_bought = int(amount / (buy_price * (1.0 + FEES)))   # 정수주
            if qty_bought <= 0:
                continue
            cost = qty_bought * buy_price
            fee = cost * FEES
            spend = cost + fee
            if spend > s["cash"]:
                continue
            new_qty = s["qty"] + qty_bought
            s["avg_price"] = (s["cost_basis"] + cost) / new_qty if new_qty > 0 else 0.0
            s["qty"] = new_qty
            s["cost_basis"] += cost
            s["cash"] -= spend
            s["cycle_idx"] += buy_fraction
            s["trades"] += 1

        total_eq = 0.0
        for t in tickers:
            s = states[t]
            mv = s["qty"] * float(row.get(t, s["avg_price"] or 0))
            total_eq += s["cash"] + mv
        equity_history.append((ts, total_eq))

    return _summarize(equity_history, states, "infinite_buying")
'''

# ── 밸류 리밸런싱(VR) — run_value_rebalancing 1:1 미러링(엔진 본문에서 채움) ──
# VR 본문은 _build_vr_body() 가 엔진 소스 라인을 반영해 생성한다(아래).

_SUMMARIZE = '''

def _summarize(equity_history, states, strategy):
    eq_series = pd.Series([v for _, v in equity_history], index=[d for d, _ in equity_history])
    daily_ret = eq_series.pct_change().fillna(0.0)
    total_return_pct = (eq_series.iloc[-1] / INITIAL_CAPITAL - 1.0) * 100.0
    days = (eq_series.index[-1] - eq_series.index[0]).days or 1
    years = days / 365.25
    cagr_pct = (((eq_series.iloc[-1] / INITIAL_CAPITAL) ** (1.0 / years) - 1.0) * 100.0
                if years > 0 and eq_series.iloc[-1] > 0 else 0.0)
    roll_max = eq_series.cummax()
    mdd_pct = ((eq_series / roll_max) - 1.0).min() * 100.0
    vol_annual = daily_ret.std() * np.sqrt(252) * 100.0
    sharpe = (daily_ret.mean() / daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0.0
    win_rate = (daily_ret > 0).sum() / max(1, (daily_ret != 0).sum()) * 100.0
    total_trades = sum(s["trades"] for s in states.values())
    completed_cycles = sum(s.get("cycles_completed", 0) for s in states.values())
    step = max(1, len(eq_series) // 365)
    eq_points = [{"date": str(d.date()), "value": _round(v)} for d, v in eq_series.iloc[::step].items()]
    return {
        "strategy": strategy,
        "stats": {
            "total_return_pct": _round(total_return_pct),
            "annualized_return_pct": _round(cagr_pct),
            "max_drawdown_pct": _round(mdd_pct),
            "sharpe": _round(sharpe),
            "volatility_pct": _round(vol_annual),
            "win_rate_pct": _round(win_rate),
            "trades": total_trades,
            "cycles_completed": completed_cycles,
            "final_equity": _round(eq_series.iloc[-1]),
        },
        "equity_curve": eq_points,
    }
'''

_MAIN = '''

if __name__ == "__main__":
    # 예시: yfinance 등으로 종가/고가를 만들어 실행
    #   import yfinance as yf
    #   df = yf.download(TICKERS[0], period="10y")
    #   closes = {TICKERS[0]: df["Close"]}; highs = {TICKERS[0]: df["High"]}
    #   print(run(closes, highs)["stats"])
    print("config:", dict(TICKERS=TICKERS, SPLIT=SPLIT, TAKE_PROFIT_PCT=TAKE_PROFIT_PCT))
'''


def _ib_config_block(c: Dict[str, Any]) -> str:
    tickers = c.get("tickers") or ["TQQQ"]
    return (
        f"\n# ── config (워크스페이스 설정) ──\n"
        f"TICKERS = {tickers!r}\n"
        f"SPLIT = {int(c.get('split', 40))}\n"
        f"TAKE_PROFIT_PCT = {float(c.get('take_profit_pct', 10.0))}\n"
        f"LOC_OFFSET_PCT = {float(c.get('loc_offset_pct', 15.0))}\n"
        f"INITIAL_CAPITAL = {float(c.get('initial_capital', 10000.0))}\n"
        f"FEES = {float(c.get('fees', 0.0025))}\n"
        f"SLIPPAGE = {float(c.get('slippage', 0.001))}\n"
    )


def generate_portfolio_strategy(strategy: str, config: Dict[str, Any], market: str = "us") -> str:
    """config → 독립 실행 가능한 전략 .py 소스 문자열."""
    if strategy == "infinite_buying":
        header = _HEADER.format(title="무한매수법 (Infinite Buying)",
                                engine_fn="run_infinite_buying")
        code = header + _ib_config_block(config) + _IB_BODY + _SUMMARIZE + _MAIN
    elif strategy == "value_rebalancing":
        # 2차 목표(VR 미러링) — IB parity 확립 후 동일 패턴으로 확장.
        raise NotImplementedError(
            "value_rebalancing codegen 은 2차 작업입니다(IB 미러링 패턴 확립 후 추가)."
        )
    else:
        raise ValueError(f"지원하지 않는 전략: {strategy} (가능: {PORTFOLIO_STRATEGIES})")

    # 구문 검증 — 생성 즉시 compile 로 SyntaxError 차단
    compile(code, f"<generated:{strategy}>", "exec")
    return code
